#!/usr/bin/env python3
"""Find dashes that read as machine prose, in the text this site writes itself.

The house rule, from for-agents/STYLE.md: dashes are unspaced, and an em dash
appears only in a pair, the way brackets do. A lone em dash with spaces around
it is the habit of a language model rather than of this centre, and it is the
single clearest tell in a page that was drafted with help.

What counts as an offence:

  spaced      " -- ", " — " or " – " used to break a sentence. A comma, a
              colon, a full stop or a pair of brackets says the same thing.
              A spaced hyphen is not checked, because a list marker at the
              start of a line looks exactly the same to a regular expression.
  lone        one em dash on a line, whether spaced or not: a pair or nothing.

What does not:

  en dash between two concepts or two bounds, "nob-nno", "2020-2024", written
  with an en dash and no spaces. That is what an en dash is for.

Text this site did not write is left alone: records synced from an external
API, a partner's own words, a person's own biography. Restyling someone else's
sentence is not a style fix. Those paths are listed in IMPORTED below, and a
generated file is recognised by its own "Generated by" first line.

Usage:
  python3 scripts/check_dashes.py                 # report, exit 1 if anything is found
  python3 scripts/check_dashes.py --all           # include the imported text, for information
  python3 scripts/check_dashes.py --path site/about
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

IMPORTED = (
    "site/_directory/",          # people and projects, synced from NVA and written by them
    "site/_data/mishmash_results.yml",
    "site/_data/partner_news.yml",
    "site/_data/partner_events.yml",
    "site/_data/wikidata_institutions.yml",
    "site/_data/zenodo_records.yml",
    "site/_data/results_openalex.yml",
    "site/_data/member_posts.yml",
    "site/_data/research_catalogue.yml",
    "site/_data/freesound.yml",
)

# Dashes that stay, each one somebody else's punctuation. A path and a piece of
# the line, so that a new offence on the same line is still reported.
ALLOWED = [
    # an organisation's own name, as it writes it
    ("site/_data/partners.yml", "Norsus – Norsk institutt"),
    ("site/_data/partners.yml", "Aldea — Center for Contemporary Art"),
    ("site/_data/partners.yml", "Ultima – Oslo Contemporary Music Festival"),
    ("site/_data/partners.yml", "Ultima – Oslo samtidsmusikkfestival"),
    ("site/_events/kristiania2027/index.md", "KAI — Kristiania AI Centre"),
    ("site/_events/2026-08-20-meshup19.md", "meemoo – the Flemish Institute"),
    # a speaker's own abstract or biography, quoted as they wrote it
    ("site/_events/2026-02-12-meshup03.md", "The interpretation of human movement"),
    ("site/_events/2026-03-12-meshup07.md", "Sports organizations and broadcasters"),
    ("site/_events/2026-05-28-meshup15.md", "Recent advances in AI have generated"),
    ("site/_events/2026-09-03-meshup21.md", "Image sonification"),
    ("site/_events/2026-09-10-meshup22.md", "This presentation will introduce"),
    # the title of somebody else's page or project
    ("site/_news/2026-09-10-sustainable-ai-seed-project.md", "Potsdam Institute for Climate Impact Research"),
    ("site/internal/funding/seed-funding/seed02/index.md", "Human and Machine Improvisation"),
]


def allowed(path: str, line: str) -> bool:
    return any(path == where and what in line for where, what in ALLOWED)


SPACED = re.compile(r"\s(—|–|--)\s")
EM = re.compile(r"—")
CODE_FENCE = re.compile(r"^\s*(```|~~~)")
QUOTED = re.compile(r"\*[^*\n]+\*|\"[^\"\n]+\"|\u201c[^\u201d\n]+\u201d|«[^»\n]+»|`[^`\n]+`")


ENTITIES = {"&mdash;": "\u2014", "&ndash;": "\u2013", "&#8212;": "\u2014", "&#8211;": "\u2013",
            "&#x2014;": "\u2014", "&#x2013;": "\u2013"}


def decoded(line: str) -> str:
    """A dash written as an HTML entity is still a dash on the page.

    The site footer carried six of them for months, invisible to a check that
    only looked for the character itself.
    """
    for entity, character in ENTITIES.items():
        line = line.replace(entity, character)
    return line


def without_quotations(line: str) -> str:
    """Blank out italics, quotation marks and code, which quote someone else."""
    return QUOTED.sub(lambda m: " " * len(m.group(0)), line)


def is_imported(path: str) -> bool:
    return any(path.startswith(prefix) for prefix in IMPORTED)


def offences(path: Path) -> list[tuple[int, str, str]]:
    """(line number, what is wrong, the line) for each dash that breaks the rule."""
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return []
    if path.suffix in (".md", ".yml") and text.startswith("# Generated by"):
        return []
    found = []
    in_code = False
    for number, line in enumerate(text.split("\n"), 1):
        if CODE_FENCE.match(line):
            in_code = not in_code
            continue
        if in_code:
            continue
        if allowed(str(path), line):
            continue
        own = without_quotations(decoded(line))
        if SPACED.search(own):
            found.append((number, "spaced dash", line.strip()))
        elif EM.findall(own) and len(EM.findall(own)) % 2 == 1:
            found.append((number, "lone em dash", line.strip()))
    return found


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--all", action="store_true", help="include imported text")
    ap.add_argument("--path", default="site", help="limit to this path")
    args = ap.parse_args()

    tracked = subprocess.run(
        ["git", "ls-files", args.path], capture_output=True, text=True, check=True
    ).stdout.split()

    total = 0
    skipped = 0
    for name in sorted(tracked):
        if Path(name).suffix not in (".md", ".html", ".yml"):
            continue
        if is_imported(name) and not args.all:
            skipped += 1
            continue
        found = offences(Path(name))
        if not found:
            continue
        print(f"\n{name}")
        for number, what, line in found:
            print(f"  {number:>4}  {what:<13} {line[:110]}")
        total += len(found)

    print(f"\n{total} to fix" + (f", {skipped} imported files left alone" if skipped else ""))
    return 1 if total else 0


if __name__ == "__main__":
    raise SystemExit(main())
