#!/usr/bin/env python3
"""Generate commit statistics for the AI colophon page.

Counts commits in the repository and how many carry an AI co-author
trailer (Co-Authored-By: Claude/Copilot/…), lists the latest commits
(subject, date, and how each was made — no author names or emails),
and writes the result to site/_data/ai_colophon.yml for the
/about/ai-colophon/ pages.
"""
import datetime
import re
import subprocess

import yaml

from repo_paths import SITE_ROOT

AI_TRAILER = r"^Co-Authored-By: (Claude|GitHub Copilot|Copilot|ChatGPT|Gemini)"
RECENT_COUNT = 5


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], capture_output=True, text=True, check=True,
        cwd=SITE_ROOT.parent,
    ).stdout.strip()


def recent_commits() -> list:
    """The latest commits as date + subject + how they were made."""
    entries = []
    log = git(
        "log", f"-{RECENT_COUNT}", "--format=%H%x1f%as%x1f%an%x1f%s%x1f%b%x1e"
    )
    for record in log.split("\x1e"):
        record = record.strip("\n")
        if not record.strip():
            continue
        sha, date, author, subject, body = record.split("\x1f")
        if author.endswith("[bot]"):
            how = "automated"
        elif re.search(AI_TRAILER, body, flags=re.MULTILINE):
            how = "ai_assisted"
        else:
            how = "human"
        entries.append({"date": date, "subject": subject, "how": how})
    return entries


def main() -> None:
    total = int(git("rev-list", "--count", "HEAD"))
    ai_hashes = git(
        "log", "--extended-regexp", f"--grep={AI_TRAILER}", "--format=%H"
    ).splitlines()
    first_ai = (
        git("log", "--format=%as", ai_hashes[-1], "-1") if ai_hashes else None
    )
    recent = recent_commits()

    out = SITE_ROOT / "_data" / "ai_colophon.yml"
    data = {
        "total_commits": total,
        "ai_assisted_commits": len(ai_hashes),
        "first_ai_commit": first_ai,
        "updated": datetime.date.today().isoformat(),
        "recent_commits": recent,
    }
    out.write_text(
        "# Generated by scripts/generate_ai_colophon_stats.py — do not edit.\n"
        + yaml.safe_dump(data, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )
    print(f"Wrote {out}: {len(ai_hashes)}/{total} commits AI-assisted, "
          f"{len(recent)} recent commits listed")


if __name__ == "__main__":
    main()
