#!/usr/bin/env python3
"""Generate commit statistics for the AI colophon page.

Counts commits in the repository and how many carry an AI co-author
trailer (Co-Authored-By: Claude/Copilot/…), and writes the result to
site/_data/ai_colophon.yml for the /about/ai-colophon/ pages.
"""
import datetime
import subprocess

from repo_paths import SITE_ROOT

AI_TRAILER = r"^Co-Authored-By: (Claude|GitHub Copilot|Copilot|ChatGPT|Gemini)"


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], capture_output=True, text=True, check=True,
        cwd=SITE_ROOT.parent,
    ).stdout.strip()


def main() -> None:
    total = int(git("rev-list", "--count", "HEAD"))
    ai_hashes = git(
        "log", "--extended-regexp", f"--grep={AI_TRAILER}", "--format=%H"
    ).splitlines()
    first_ai = (
        git("log", "--format=%as", ai_hashes[-1], "-1") if ai_hashes else None
    )

    out = SITE_ROOT / "_data" / "ai_colophon.yml"
    out.write_text(
        "# Generated by scripts/generate_ai_colophon_stats.py — do not edit.\n"
        f"total_commits: {total}\n"
        f"ai_assisted_commits: {len(ai_hashes)}\n"
        f"first_ai_commit: {first_ai}\n"
        f"updated: {datetime.date.today().isoformat()}\n",
        encoding="utf-8",
    )
    print(f"Wrote {out}: {len(ai_hashes)}/{total} commits AI-assisted")


if __name__ == "__main__":
    main()
