#!/usr/bin/env python3
"""Generate commit statistics for the AI colophon page.

Counts commits in the repository and how many carry an explicit,
machine-readable AI marker — a Co-Authored-By trailer from any of the
agents used on this repo (Claude, Copilot, ChatGPT, Gemini, Cursor, …)
or authorship by a coding-agent bot. AI assistance has been used since
the very first commit, but early commits were not systematically
marked, so this is a lower bound, and the colophon says so.

Also lists the latest commits (subject, date, and how each was made —
no author names or emails) and writes everything to
site/_data/ai_colophon.yml for the /about/ai-colophon/ pages.
"""
import datetime
import re
import subprocess

import yaml

from repo_paths import SITE_ROOT

AI_TRAILER = r"^Co-Authored-By:.*(Claude|Copilot|ChatGPT|Gemini|Cursor|Aider|Codex|Devin|anthropic\.com|cursor\.com)"
AI_AUTHOR = r"(copilot-swe-agent|cursoragent|devin-ai|aider)"
AUTOMATION_AUTHOR = r"^github-actions\[bot\]$"
RECENT_COUNT = 5


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], capture_output=True, text=True, check=True,
        cwd=SITE_ROOT.parent,
    ).stdout.strip()


def recent_commits() -> list:
    """The latest commits as date + subject + how they were made."""
    entries = []
    log = git(
        "log", f"-{RECENT_COUNT}", "--format=%H%x1f%as%x1f%an%x1f%s%x1f%b%x1e"
    )
    for record in log.split("\x1e"):
        record = record.strip("\n")
        if not record.strip():
            continue
        sha, date, author, subject, body = record.split("\x1f")
        if re.search(AUTOMATION_AUTHOR, author):
            how = "automated"
        elif re.search(AI_AUTHOR, author, flags=re.IGNORECASE) or re.search(
            AI_TRAILER, body, flags=re.MULTILINE | re.IGNORECASE
        ):
            how = "ai_assisted"
        else:
            how = "human"
        entries.append({"date": date, "subject": subject, "how": how})
    return entries


def main() -> None:
    total = int(git("rev-list", "--count", "HEAD"))
    trailer_hashes = set(
        git(
            "log", "--extended-regexp", "--regexp-ignore-case",
            f"--grep={AI_TRAILER}", "--format=%H",
        ).splitlines()
    )
    author_hashes = set(
        git(
            "log", "--extended-regexp", "--regexp-ignore-case",
            f"--author={AI_AUTHOR}", "--format=%H",
        ).splitlines()
    )
    marked = trailer_hashes | author_hashes
    recent = recent_commits()

    out = SITE_ROOT / "_data" / "ai_colophon.yml"
    data = {
        "total_commits": total,
        # Lower bound: commits carrying an explicit AI marker. AI
        # assistance predates systematic marking on this repo.
        "ai_marked_commits": len(marked),
        "updated": datetime.date.today().isoformat(),
        "recent_commits": recent,
    }
    out.write_text(
        "# Generated by scripts/generate_ai_colophon_stats.py — do not edit.\n"
        + yaml.safe_dump(data, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )
    print(f"Wrote {out}: {len(marked)}/{total} commits carry an AI marker, "
          f"{len(recent)} recent commits listed")


if __name__ == "__main__":
    main()
